name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master
    - staging

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build website
      env:
        # Optional base url set in repo secrets e.g. /rchain-docs/
        # Workaround for https://github.com/facebook/docusaurus/issues/448
        BASE_URL: ${{ secrets.BASE_URL }}
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

  # Job to notify bors when run is successful. Skipped and cancelled job is considered
  # as failure. More info https://github.com/bors-ng/bors-ng/issues/1115.
  bors_success:
    name: bors build finished
    needs:
    - deploy
    if: "github.event_name == 'push' && (github.ref == 'refs/heads/trying' || github.ref == 'refs/heads/staging') && success()"
    runs-on: ubuntu-latest
    steps:
    - run: true
